### ISSUE TITLE
Web project is not building

### ISSUE THREAD

**Issue by eliassal** [microsoft/PartsUnlimited#218]
I have just downloaded and opened PartsUnlimited.sln the code in VS 2K19 18.6. After restoring, trying to build, I get

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8036	The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [M:\AzureDevOpsServer\.NetConf\Demos\forkPU\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\node-sass\build\src\libsass.vcxproj]	PartsUnlimitedWebsite	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets	36	
Error	MSB8036	The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [M:\AzureDevOpsServer\.NetConf\Demos\forkPU\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\node-sass\build\src\libsass.vcxproj]	PartsUnlimitedWebsite	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets	36	
Error		`C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1	PartsUnlimitedWebsite	M:\AzureDevOpsServer\.NetConf\Demos\forkPU\PartsUnlimited\src\PartsUnlimitedWebsite\EXEC	1	
Error	code	1	PartsUnlimitedWebsite	M:\AzureDevOpsServer\.NetConf\Demos\forkPU\PartsUnlimited\src\PartsUnlimitedWebsite\EXEC	1	
Error	MSB3073	The command "npm install python2" exited with code 1.	PartsUnlimitedWebsite	M:\AzureDevOpsServer\.NetConf\Demos\forkPU\PartsUnlimited\src\PartsUnlimitedWebsite\PartsUnlimitedWebsite.csproj	39
```	

Deleted node_modules folder did npm install I get other errors as follows

```
Project "...\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.sln" (1) is buildin
g "...\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on
node 1 (default targets).
Project "....\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (
2) is building "....\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\src\libsass.vcxproj"
 (3) on node 1 (default targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. I
nstall the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [...\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\src\libsass.vcxproj]
Done Building Project "....\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\src\libsass.v
cxproj" (default targets) -- FAILED.

Done Building Project "....\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.vcxpr
oj.metaproj" (default targets) -- FAILED.

Done Building Project "...\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.sln"
(default targets) -- FAILED.


Build FAILED.

"...\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.sln" (default target) (1) -
>
".....\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (default
target) (2) ->
"....\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\src\libsass.vcxproj" (default targe
t) (3) ->
(Desktop_PlatformPrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found.
 Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [...\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\src\libsass.vcxproj]

    1 Error(s)

Time Elapsed 00:00:12.63
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (...\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" ".....\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd .....\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN PartsUnlimited@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ....\AppData\Roaming\npm-cache\_logs\2020-12-02T17_07_23_179Z-debug.log

```

**Comment by eliassal** [comment]
As you can notice in the snapshot, solution and project have the red swiggly line
![PU-NoBuild](https://user-images.githubusercontent.com/8447864/100910645-84272f80-34ce-11eb-9062-9041e68df164.jpg)

**Comment by eliassal** [comment]
I cleaned everything, recloned the repo, also, did 
npm install grunt --save-dev
fired VS 2k19 and opened the web project, always errors as follows

```
Build started...
1>------ Build started: Project: PartsUnlimited.Models, Configuration: Debug Any CPU ------
1>PartsUnlimited.Models -> M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimited.Models\bin\Debug\netcoreapp2.2\PartsUnlimited.Models.dll
2>------ Build started: Project: PartsUnlimitedWebsite, Configuration: Debug Any CPU ------
2>
2>> node-sass@3.13.1 install M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass
2>> node scripts/install.js
2>
2>Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node
2>Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node":
2>
2>HTTP error 404 Not Found
2>
2>Hint: If github.com is not accessible in your location
2>      try setting a proxy via HTTP_PROXY, e.g.
2>
2>      export HTTP_PROXY=http://example.com:1234
2>
2>or configure npm proxy via
2>
2>      npm config set proxy http://example.com:8080
2>
2>> node-sass@4.11.0 install M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\node-sass
2>> node scripts/install.js
2>
2>Cached binary found at C:\Users\salam.SALAM\AppData\Roaming\npm-cache\node-sass\4.11.0\win32-x64-64_binding.node
2>
2>> node-sass@3.13.1 postinstall M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass
2>> node scripts/build.js
2>
2>Building: C:\Program Files\nodejs\node.exe M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
2>gyp info it worked if it ends with ok
2>gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
2>gyp verb cli   'M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\node-gyp\\bin\\node-gyp.js',
2>gyp verb cli   'rebuild',
2>gyp verb cli   '--verbose',
2>gyp verb cli   '--libsass_ext=',
2>gyp verb cli   '--libsass_cflags=',
2>gyp verb cli   '--libsass_ldflags=',
2>gyp verb cli   '--libsass_library=' ]
2>gyp info using node-gyp@3.8.0
2>gyp info using node@10.13.0 | win32 | x64
2>gyp verb command rebuild []
2>gyp verb command clean []
2>gyp verb clean removing "build" directory
2>gyp verb command configure []
2>gyp verb check python checking for Python executable "python2.7" in the PATH
2>EXEC : gyp verb `which` failed error : not found: python2.7
2>gyp verb `which` failed     at getNotFoundError (M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\which\which.js:13:12)
2>gyp verb `which` failed     at F (M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\which\which.js:68:19)
2>gyp verb `which` failed     at E (M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\which\which.js:80:29)
2>gyp verb `which` failed     at M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\which\which.js:89:16
2>gyp verb `which` failed     at M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\isexe\index.js:42:5
2>gyp verb `which` failed     at M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\isexe\windows.js:36:5
2>gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
2>EXEC : gyp verb `which` failed  python2.7 { error : not found: python2.7
2>gyp verb `which` failed     at getNotFoundError (M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\which\which.js:13:12)
2>gyp verb `which` failed     at F (M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\which\which.js:68:19)
2>gyp verb `which` failed     at E (M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\which\which.js:80:29)
2>gyp verb `which` failed     at M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\which\which.js:89:16
2>gyp verb `which` failed     at M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\isexe\index.js:42:5
2>gyp verb `which` failed     at M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\isexe\windows.js:36:5
2>gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
2>gyp verb `which` failed   stack:
2>gyp verb `which` failed    'Error: not found: python2.7\n    at getNotFoundError (M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\which\\which.js:13:12)\n    at F (M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\which\\which.js:68:19)\n    at E (M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\which\\which.js:80:29)\n    at M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\which\\which.js:89:16\n    at M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\isexe\\index.js:42:5\n    at M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
2>gyp verb `which` failed   code: 'ENOENT' }
2>gyp verb could not find "python2.7". checking python launcher
2>gyp verb check python launcher python executable found: "C:\\Users\\salam.SALAM\\.windows-build-tools\\python27\\python.exe"
2>gyp verb check python version `C:\Users\salam.SALAM\.windows-build-tools\python27\python.exe -c "import sys; print "2.7.14
2>gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
2>gyp verb get node dir no --target version specified, falling back to host node version: 10.13.0
2>gyp verb command install [ '10.13.0' ]
2>gyp verb install input version string "10.13.0"
2>gyp verb install installing version: 10.13.0
2>gyp verb install --ensure was passed, so won't reinstall if already installed
2>gyp verb install version is already installed, need to check "installVersion"
2>gyp verb got "installVersion" 9
2>gyp verb needs "installVersion" 9
2>gyp verb install version is good
2>gyp verb get node dir target node version installed: 10.13.0
2>gyp verb build dir attempting to create "build" dir: M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build
2>gyp verb build dir "build" dir needed to be created? M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build
2>gyp verb build/config.gypi creating config file
2>gyp verb build/config.gypi writing out config file: M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\config.gypi
2>gyp verb config.gypi checking for gypi file: M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\config.gypi
2>gyp verb common.gypi checking for gypi file: M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\common.gypi
2>gyp verb gyp gyp format was not specified; forcing "msvs"
2>gyp info spawn C:\Users\salam.SALAM\.windows-build-tools\python27\python.exe
2>gyp info spawn args [ 'M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\node-gyp\\gyp\\gyp_main.py',
2>gyp info spawn args   'binding.gyp',
2>gyp info spawn args   '-f',
2>gyp info spawn args   'msvs',
2>gyp info spawn args   '-G',
2>gyp info spawn args   'msvs_version=2015',
2>gyp info spawn args   '-I',
2>gyp info spawn args   'M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\grunt-sass\\node_modules\\node-sass\\build\\config.gypi',
2>gyp info spawn args   '-I',
2>gyp info spawn args   'M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\node-gyp\\addon.gypi',
2>gyp info spawn args   '-I',
2>gyp info spawn args   'C:\\Users\\salam.SALAM\\.node-gyp\\10.13.0\\include\\node\\common.gypi',
2>gyp info spawn args   '-Dlibrary=shared_library',
2>gyp info spawn args   '-Dvisibility=default',
2>gyp info spawn args   '-Dnode_root_dir=C:\\Users\\salam.SALAM\\.node-gyp\\10.13.0',
2>gyp info spawn args   '-Dnode_gyp_dir=M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\node-gyp',
2>gyp info spawn args   '-Dnode_lib_file=C:\\Users\\salam.SALAM\\.node-gyp\\10.13.0\\<(target_arch)\\node.lib',
2>gyp info spawn args   '-Dmodule_root_dir=M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\grunt-sass\\node_modules\\node-sass',
2>gyp info spawn args   '-Dnode_engine=v8',
2>gyp info spawn args   '--depth=.',
2>gyp info spawn args   '--no-parallel',
2>gyp info spawn args   '--generator-output',
2>gyp info spawn args   'M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\grunt-sass\\node_modules\\node-sass\\build',
2>gyp info spawn args   '-Goutput_dir=.' ]
2>gyp verb command build []
2>gyp verb build type Release
2>gyp verb architecture x64
2>gyp verb node dev dir C:\Users\salam.SALAM\.node-gyp\10.13.0
2>gyp verb found first Solution file build/binding.sln
2>gyp verb could not find "msbuild.exe" in PATH - finding location in registry
2>gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
2>gyp info spawn args [ 'build/binding.sln',
2>gyp info spawn args   '/nologo',
2>gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
2>Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
2>Build started 03/12/2020 09:34:26.
2>Project "M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
2>ValidateSolutionConfiguration:
2>  Building solution configuration "Release|x64".
2>Project "M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.sln" (1) is building "M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
2>Project "M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targets).
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\src\libsass.vcxproj]
2>Done Building Project "M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILED.
2>Done Building Project "M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.
2>Done Building Project "M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.
2>
2>Build FAILED.
2>
2>"M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.sln" (default target) (1) ->
2>"M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
2>"M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
2>(Desktop_PlatformPrepareForBuild target) ->
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass\build\src\libsass.vcxproj]
2>
2>    0 Warning(s)
2>    1 Error(s)
2>
2>Time Elapsed 00:00:00.79
2>gyp ERR! build error
2>EXEC : gyp ERR! stack error : `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
2>gyp ERR! stack     at ChildProcess.onExit (M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\node-gyp\lib\build.js:262:23)
2>gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
2>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
2>gyp ERR! System Windows_NT 10.0.19041
2>gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "M:\\AzureDevOpsServer\\.NetConf\\Demos\\danroth27-PartsUnlimited\\PartsUnlimited\\src\\PartsUnlimitedWebsite\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
2>gyp ERR! cwd M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\node_modules\grunt-sass\node_modules\node-sass
2>gyp ERR! node -v v10.13.0
2>gyp ERR! node-gyp -v v3.8.0
2>gyp ERR! not ok
2>EXEC : Build failed with error code: 1
2>npm WARN PartsUnlimited@0.0.0 No license field.
2>
2>npm ERR! code ELIFECYCLE
2>npm ERR! errno 1
2>npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
2>npm ERR! Exit status 1
2>npm ERR!
2>npm ERR! Failed at the node-sass@3.13.1 postinstall script.
2>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2>
2>npm ERR! A complete log of this run can be found in:
2>npm ERR!     C:\Users\salam.SALAM\AppData\Roaming\npm-cache\_logs\2020-12-03T08_34_28_321Z-debug.log
2>M:\AzureDevOpsServer\.NetConf\Demos\danroth27-PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\PartsUnlimitedWebsite.csproj(38,5): error MSB3073: The command "npm install --python=python2.7" exited with code 1.
2>Done building project "PartsUnlimitedWebsite.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
